# Generated by Django 6.0.3 on 2026-03-24 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers le projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifie le'),
        ),
    ]
